name: Automatización Binance Transfi

on:
  schedule:
    - cron: '15 12 * * *' # 8:15 AM hora de Venezuela (12:15 PM UTC)
    - cron: '30 17 * * *' # 1:30 PM hora de Venezuela (5:30 PM UTC)
  workflow_dispatch: # Permite ejecutar manualmente el workflow desde la pestaña Actions

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar permisos de archivos
        run: |
          ls -l
          ls -l ./tasas-transfi.xlsx

      - name: Configurar variables de entorno para Google y Telegram
        run: echo "Variables de entorno configuradas"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Ejecutar el script de automatización
        run: python main.py  # Cambia 'main.py' por el nombre de tu script principal
        env:
          GITHUB_ACTIONS: true
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Hacer commit de los cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tasas-transfi.xlsx
          git commit -m "Actualización automática de tasas-transfi.xlsx"
          git push

      - name: Notificar éxito
        if: success()
        run: echo "El script se ejecutó correctamente."

      - name: Notificar fallo
        if: failure()
        run: echo "El script falló."

        